CRITICAL - 2023-05-24 04:52:07 --> Class "App\Controllers\ApiModel" not found
in APPPATH\Controllers\H31.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 04:53:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 04:53:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 04:54:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 04:54:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 04:54:59 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 04:54:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 04:55:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 04:55:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 04:55:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 04:55:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 04:55:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 04:55:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 05:01:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 05:01:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 05:08:59 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 05:08:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:10:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:10:09 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:17:59 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:17:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:23:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:23:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:23:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:23:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:23:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:23:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:23:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:23:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:24:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:24:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:24:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:24:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:24:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:24:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:24:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:24:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:24:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:24:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 06:24:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 06:24:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 08:22:05 --> number_format(): Argument #1 ($num) must be of type float, array given
in APPPATH\Controllers\H31.php on line 45.
 1 APPPATH\Controllers\H31.php(45): number_format([...], 2)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 08:25:05 --> number_format(): Argument #1 ($num) must be of type float, array given
in APPPATH\Controllers\H31.php on line 45.
 1 APPPATH\Controllers\H31.php(45): number_format([...], 2)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 08:25:07 --> number_format(): Argument #1 ($num) must be of type float, array given
in APPPATH\Controllers\H31.php on line 45.
 1 APPPATH\Controllers\H31.php(45): number_format([...], 2)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 08:57:49 --> foreach() argument must be of type array|object, float given
in APPPATH\Views\h31.php on line 26.
 1 APPPATH\Views\h31.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'foreach() argument must be of type array|object, float given', 'APPPATH\\Views\\h31.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h31.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h31', [], true)
 5 APPPATH\Controllers\H31.php(48): view('h31', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:02:41 --> foreach() argument must be of type array|object, float given
in APPPATH\Views\h31.php on line 26.
 1 APPPATH\Views\h31.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'foreach() argument must be of type array|object, float given', 'APPPATH\\Views\\h31.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h31.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h31', [], true)
 5 APPPATH\Controllers\H31.php(48): view('h31', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:02:42 --> foreach() argument must be of type array|object, float given
in APPPATH\Views\h31.php on line 26.
 1 APPPATH\Views\h31.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'foreach() argument must be of type array|object, float given', 'APPPATH\\Views\\h31.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h31.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h31', [], true)
 5 APPPATH\Controllers\H31.php(48): view('h31', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:05:40 --> Cannot use [] for reading
in APPPATH\Controllers\H31.php on line 36.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-24 09:05:53 --> foreach() argument must be of type array|object, float given
in APPPATH\Views\h31.php on line 26.
 1 APPPATH\Views\h31.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'foreach() argument must be of type array|object, float given', 'APPPATH\\Views\\h31.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h31.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h31', [], true)
 5 APPPATH\Controllers\H31.php(48): view('h31', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:06:18 --> Undefined variable $averages
in APPPATH\Views\h31.php on line 26.
 1 APPPATH\Views\h31.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $averages', 'APPPATH\\Views\\h31.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h31.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h31', [], true)
 5 APPPATH\Controllers\H31.php(48): view('h31', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:06:20 --> Undefined variable $averages
in APPPATH\Views\h31.php on line 26.
 1 APPPATH\Views\h31.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $averages', 'APPPATH\\Views\\h31.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h31.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h31', [], true)
 5 APPPATH\Controllers\H31.php(48): view('h31', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:11:26 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error

in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:11:30 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error

in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:36:59 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:37:25 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: HTTP request failed!
in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: HTTP request failed!', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:37:46 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:38:07 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:38:28 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:38:49 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-05-24 09:39:11 --> file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\h41.php on line 58.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(http://103.76.120.90/logdata): Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\h41.php', 58)
 2 APPPATH\Views\h41.php(58): file_get_contents('http://103.76.120.90/logdata')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\h41.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('h41', [], true)
 6 APPPATH\Controllers\H41.php(9): view('h41')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H41->h41()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H41))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 09:51:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 09:51:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-24 10:18:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\H31->h31()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-05-24 10:18:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\H31.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\H31->h31()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\H31))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
