ERROR - 2023-05-06 15:52:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-05-06 15:52:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logdata` (`suhu`, `kelembapan`, `created_date`, `blok`) VALUES (:suhu:, :kelembapan:, :created_date:, :blok:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Logdata.php(43): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Logdata->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-06 16:17:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-05-06 16:17:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logdata` (`suhu`, `kelembapan`, `created_date`, `blok`) VALUES (:suhu:, :kelembapan:, :created_date:, :blok:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Logdata.php(43): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Logdata->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
