ERROR - 2023-05-07 02:08:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#5 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(648): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 E:\xampp\htdocs\logdata1\logdata\system\Commands\Database\MigrateStatus.php(112): CodeIgniter\Database\MigrationRunner->getHistory('')
#8 E:\xampp\htdocs\logdata1\logdata\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#9 E:\xampp\htdocs\logdata1\logdata\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#10 E:\xampp\htdocs\logdata1\logdata\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#4 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(648): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 E:\xampp\htdocs\logdata1\logdata\system\Commands\Database\MigrateStatus.php(112): CodeIgniter\Database\MigrationRunner->getHistory('')
#7 E:\xampp\htdocs\logdata1\logdata\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#9 E:\xampp\htdocs\logdata1\logdata\spark(97): CodeIgniter\CLI\Console->run()
#10 {main}
CRITICAL - 2023-05-07 02:08:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `db_kel7`')
 3 SYSTEMPATH\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
 5 SYSTEMPATH\Database\MigrationRunner.php(648): CodeIgniter\Database\MigrationRunner->ensureTable()
 6 SYSTEMPATH\Commands\Database\MigrateStatus.php(112): CodeIgniter\Database\MigrationRunner->getHistory('ROOTPATH\\public')
 7 SYSTEMPATH\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateStatus->run([])
 8 SYSTEMPATH\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:status', [])
 9 ROOTPATH\spark(97): CodeIgniter\CLI\Console->run()
ERROR - 2023-05-07 02:12:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#5 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(648): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 E:\xampp\htdocs\logdata1\logdata\system\Commands\Database\MigrateStatus.php(112): CodeIgniter\Database\MigrationRunner->getHistory('')
#8 E:\xampp\htdocs\logdata1\logdata\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#9 E:\xampp\htdocs\logdata1\logdata\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#10 E:\xampp\htdocs\logdata1\logdata\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#4 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 E:\xampp\htdocs\logdata1\logdata\system\Database\MigrationRunner.php(648): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 E:\xampp\htdocs\logdata1\logdata\system\Commands\Database\MigrateStatus.php(112): CodeIgniter\Database\MigrationRunner->getHistory('')
#7 E:\xampp\htdocs\logdata1\logdata\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#9 E:\xampp\htdocs\logdata1\logdata\spark(97): CodeIgniter\CLI\Console->run()
#10 {main}
CRITICAL - 2023-05-07 02:12:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `db_kel7`')
 3 SYSTEMPATH\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
 5 SYSTEMPATH\Database\MigrationRunner.php(648): CodeIgniter\Database\MigrationRunner->ensureTable()
 6 SYSTEMPATH\Commands\Database\MigrateStatus.php(112): CodeIgniter\Database\MigrationRunner->getHistory('ROOTPATH\\public')
 7 SYSTEMPATH\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateStatus->run([])
 8 SYSTEMPATH\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:status', [])
 9 ROOTPATH\spark(97): CodeIgniter\CLI\Console->run()
ERROR - 2023-05-07 09:15:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-05-07 09:15:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logdata` (`suhu`, `kelembapan`, `created_date`, `blok`) VALUES (:suhu:, :kelembapan:, :created_date:, :blok:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Logdata.php(43): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Logdata->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-07 09:18:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'phpmyadmin'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-05-07 09:18:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logdata` (`suhu`, `kelembapan`, `created_date`, `blok`) VALUES (:suhu:, :kelembapan:, :created_date:, :blok:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Logdata.php(43): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Logdata->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-05-07 09:46:17 --> mysqli_sql_exception: Unknown column 'waktu' in 'field list' in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pe...', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Penyiraman.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Penyiraman->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penyiraman))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}
ERROR - 2023-05-07 09:52:22 --> mysqli_sql_exception: Unknown column 'blok' in 'field list' in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `lo...', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}
ERROR - 2023-05-07 09:52:45 --> mysqli_sql_exception: Unknown column 'blok' in 'field list' in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `lo...', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}
ERROR - 2023-05-07 09:53:09 --> mysqli_sql_exception: Unknown column 'blok' in 'field list' in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `lo...', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}
